spring:
  application:
    name: learning-spring-samples

# actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /application
      exposure:
        include: '*'

