// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GreetingsColumns holds the columns for the "greetings" table.
	GreetingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "message", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// GreetingsTable holds the schema information for the "greetings" table.
	GreetingsTable = &schema.Table{
		Name:       "greetings",
		Columns:    GreetingsColumns,
		PrimaryKey: []*schema.Column{GreetingsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GreetingsTable,
	}
)

func init() {
}
