#ifndef TESTCOMPONENT_GLOBAL_H
#define TESTCOMPONENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TESTCOMPONENT_LIBRARY)
#  define TESTCOMPONENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TESTCOMPONENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TESTCOMPONENT_GLOBAL_H
