// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kratos-demo/internal/data/ent/greeting"
	"kratos-demo/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GreetingUpdate is the builder for updating Greeting entities.
type GreetingUpdate struct {
	config
	hooks    []Hook
	mutation *GreetingMutation
}

// Where appends a list predicates to the GreetingUpdate builder.
func (_u *GreetingUpdate) Where(ps ...predicate.Greeting) *GreetingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *GreetingUpdate) SetName(v string) *GreetingUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GreetingUpdate) SetNillableName(v *string) *GreetingUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *GreetingUpdate) SetMessage(v string) *GreetingUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *GreetingUpdate) SetNillableMessage(v *string) *GreetingUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GreetingUpdate) SetCreatedAt(v time.Time) *GreetingUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GreetingUpdate) SetNillableCreatedAt(v *time.Time) *GreetingUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the GreetingMutation object of the builder.
func (_u *GreetingUpdate) Mutation() *GreetingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GreetingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GreetingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GreetingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GreetingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GreetingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(greeting.Table, greeting.Columns, sqlgraph.NewFieldSpec(greeting.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(greeting.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(greeting.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(greeting.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{greeting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GreetingUpdateOne is the builder for updating a single Greeting entity.
type GreetingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GreetingMutation
}

// SetName sets the "name" field.
func (_u *GreetingUpdateOne) SetName(v string) *GreetingUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GreetingUpdateOne) SetNillableName(v *string) *GreetingUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *GreetingUpdateOne) SetMessage(v string) *GreetingUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *GreetingUpdateOne) SetNillableMessage(v *string) *GreetingUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GreetingUpdateOne) SetCreatedAt(v time.Time) *GreetingUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GreetingUpdateOne) SetNillableCreatedAt(v *time.Time) *GreetingUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the GreetingMutation object of the builder.
func (_u *GreetingUpdateOne) Mutation() *GreetingMutation {
	return _u.mutation
}

// Where appends a list predicates to the GreetingUpdate builder.
func (_u *GreetingUpdateOne) Where(ps ...predicate.Greeting) *GreetingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GreetingUpdateOne) Select(field string, fields ...string) *GreetingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Greeting entity.
func (_u *GreetingUpdateOne) Save(ctx context.Context) (*Greeting, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GreetingUpdateOne) SaveX(ctx context.Context) *Greeting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GreetingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GreetingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GreetingUpdateOne) sqlSave(ctx context.Context) (_node *Greeting, err error) {
	_spec := sqlgraph.NewUpdateSpec(greeting.Table, greeting.Columns, sqlgraph.NewFieldSpec(greeting.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Greeting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, greeting.FieldID)
		for _, f := range fields {
			if !greeting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != greeting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(greeting.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(greeting.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(greeting.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Greeting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{greeting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
