// Code generated by ent, DO NOT EDIT.

package ent

import (
	"kratos-demo/internal/data/ent/greeting"
	"kratos-demo/internal/data/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	greetingFields := schema.Greeting{}.Fields()
	_ = greetingFields
	// greetingDescCreatedAt is the schema descriptor for created_at field.
	greetingDescCreatedAt := greetingFields[2].Descriptor()
	// greeting.DefaultCreatedAt holds the default value on creation for the created_at field.
	greeting.DefaultCreatedAt = greetingDescCreatedAt.Default.(func() time.Time)
}
