server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    # 注册
    register-with-eureka: false
    # 服务url 注册和查询依赖
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

# 设置feign超时时间
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

# Feign日志配置
logging:
  level:
    com.learn.springcloud.service.IPaymentFeignService: debug
