server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          # uri: git@github.com:chinwe/learn-springcloud-config.git
          uri: https://github.com/chinwe/learn-springcloud-config.git
          skipSslValidation: true
          search-paths:
            - learn-springcloud-config
      label: master

eureka:
  client:
    # 服务url 注册和查询依赖
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka