server:
  port: 80

eureka:
  client:
    # 注册
    register-with-eureka: false
    # 服务url 注册和查询依赖
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

feign:
  hystrix:
    enabled: true
